name: frontend
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  file_picker: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/wingrow_logo.png
    # or, to include everything in the folder:
    # - assets/images/
